// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edge_parameter.proto

#ifndef PROTOBUF_INCLUDED_edge_5fparameter_2eproto
#define PROTOBUF_INCLUDED_edge_5fparameter_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_edge_5fparameter_2eproto 

namespace protobuf_edge_5fparameter_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_edge_5fparameter_2eproto
namespace intellgraph {
class EdgeParameter;
class EdgeParameterDefaultTypeInternal;
extern EdgeParameterDefaultTypeInternal _EdgeParameter_default_instance_;
}  // namespace intellgraph
namespace google {
namespace protobuf {
template<> ::intellgraph::EdgeParameter* Arena::CreateMaybeMessage<::intellgraph::EdgeParameter>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace intellgraph {

// ===================================================================

class EdgeParameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intellgraph.EdgeParameter) */ {
 public:
  EdgeParameter();
  virtual ~EdgeParameter();

  EdgeParameter(const EdgeParameter& from);

  inline EdgeParameter& operator=(const EdgeParameter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EdgeParameter(EdgeParameter&& from) noexcept
    : EdgeParameter() {
    *this = ::std::move(from);
  }

  inline EdgeParameter& operator=(EdgeParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EdgeParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EdgeParameter* internal_default_instance() {
    return reinterpret_cast<const EdgeParameter*>(
               &_EdgeParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(EdgeParameter* other);
  friend void swap(EdgeParameter& a, EdgeParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EdgeParameter* New() const final {
    return CreateMaybeMessage<EdgeParameter>(NULL);
  }

  EdgeParameter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EdgeParameter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const EdgeParameter& from);
  void MergeFrom(const EdgeParameter& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EdgeParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 vertex_in_id = 3;
  void clear_vertex_in_id();
  static const int kVertexInIdFieldNumber = 3;
  ::google::protobuf::int32 vertex_in_id() const;
  void set_vertex_in_id(::google::protobuf::int32 value);

  // int32 vertex_out_id = 4;
  void clear_vertex_out_id();
  static const int kVertexOutIdFieldNumber = 4;
  ::google::protobuf::int32 vertex_out_id() const;
  void set_vertex_out_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:intellgraph.EdgeParameter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 vertex_in_id_;
  ::google::protobuf::int32 vertex_out_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_edge_5fparameter_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EdgeParameter

// int32 id = 1;
inline void EdgeParameter::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 EdgeParameter::id() const {
  // @@protoc_insertion_point(field_get:intellgraph.EdgeParameter.id)
  return id_;
}
inline void EdgeParameter::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:intellgraph.EdgeParameter.id)
}

// string type = 2;
inline void EdgeParameter::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EdgeParameter::type() const {
  // @@protoc_insertion_point(field_get:intellgraph.EdgeParameter.type)
  return type_.GetNoArena();
}
inline void EdgeParameter::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:intellgraph.EdgeParameter.type)
}
#if LANG_CXX11
inline void EdgeParameter::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:intellgraph.EdgeParameter.type)
}
#endif
inline void EdgeParameter::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:intellgraph.EdgeParameter.type)
}
inline void EdgeParameter::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:intellgraph.EdgeParameter.type)
}
inline ::std::string* EdgeParameter::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:intellgraph.EdgeParameter.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EdgeParameter::release_type() {
  // @@protoc_insertion_point(field_release:intellgraph.EdgeParameter.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EdgeParameter::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:intellgraph.EdgeParameter.type)
}

// int32 vertex_in_id = 3;
inline void EdgeParameter::clear_vertex_in_id() {
  vertex_in_id_ = 0;
}
inline ::google::protobuf::int32 EdgeParameter::vertex_in_id() const {
  // @@protoc_insertion_point(field_get:intellgraph.EdgeParameter.vertex_in_id)
  return vertex_in_id_;
}
inline void EdgeParameter::set_vertex_in_id(::google::protobuf::int32 value) {
  
  vertex_in_id_ = value;
  // @@protoc_insertion_point(field_set:intellgraph.EdgeParameter.vertex_in_id)
}

// int32 vertex_out_id = 4;
inline void EdgeParameter::clear_vertex_out_id() {
  vertex_out_id_ = 0;
}
inline ::google::protobuf::int32 EdgeParameter::vertex_out_id() const {
  // @@protoc_insertion_point(field_get:intellgraph.EdgeParameter.vertex_out_id)
  return vertex_out_id_;
}
inline void EdgeParameter::set_vertex_out_id(::google::protobuf::int32 value) {
  
  vertex_out_id_ = value;
  // @@protoc_insertion_point(field_set:intellgraph.EdgeParameter.vertex_out_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace intellgraph

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_edge_5fparameter_2eproto
