// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex_parameter.proto

#ifndef PROTOBUF_INCLUDED_vertex_5fparameter_2eproto
#define PROTOBUF_INCLUDED_vertex_5fparameter_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_vertex_5fparameter_2eproto 

namespace protobuf_vertex_5fparameter_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_vertex_5fparameter_2eproto
namespace intellgraph {
class VertexParameter;
class VertexParameterDefaultTypeInternal;
extern VertexParameterDefaultTypeInternal _VertexParameter_default_instance_;
}  // namespace intellgraph
namespace google {
namespace protobuf {
template<> ::intellgraph::VertexParameter* Arena::CreateMaybeMessage<::intellgraph::VertexParameter>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace intellgraph {

// ===================================================================

class VertexParameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intellgraph.VertexParameter) */ {
 public:
  VertexParameter();
  virtual ~VertexParameter();

  VertexParameter(const VertexParameter& from);

  inline VertexParameter& operator=(const VertexParameter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VertexParameter(VertexParameter&& from) noexcept
    : VertexParameter() {
    *this = ::std::move(from);
  }

  inline VertexParameter& operator=(VertexParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VertexParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VertexParameter* internal_default_instance() {
    return reinterpret_cast<const VertexParameter*>(
               &_VertexParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(VertexParameter* other);
  friend void swap(VertexParameter& a, VertexParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VertexParameter* New() const final {
    return CreateMaybeMessage<VertexParameter>(NULL);
  }

  VertexParameter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VertexParameter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VertexParameter& from);
  void MergeFrom(const VertexParameter& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VertexParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 dims = 4;
  void clear_dims();
  static const int kDimsFieldNumber = 4;
  ::google::protobuf::int32 dims() const;
  void set_dims(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:intellgraph.VertexParameter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 dims_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_vertex_5fparameter_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VertexParameter

// int32 id = 1;
inline void VertexParameter::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 VertexParameter::id() const {
  // @@protoc_insertion_point(field_get:intellgraph.VertexParameter.id)
  return id_;
}
inline void VertexParameter::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:intellgraph.VertexParameter.id)
}

// string type = 2;
inline void VertexParameter::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VertexParameter::type() const {
  // @@protoc_insertion_point(field_get:intellgraph.VertexParameter.type)
  return type_.GetNoArena();
}
inline void VertexParameter::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:intellgraph.VertexParameter.type)
}
#if LANG_CXX11
inline void VertexParameter::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:intellgraph.VertexParameter.type)
}
#endif
inline void VertexParameter::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:intellgraph.VertexParameter.type)
}
inline void VertexParameter::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:intellgraph.VertexParameter.type)
}
inline ::std::string* VertexParameter::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:intellgraph.VertexParameter.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VertexParameter::release_type() {
  // @@protoc_insertion_point(field_release:intellgraph.VertexParameter.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VertexParameter::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:intellgraph.VertexParameter.type)
}

// int32 dims = 4;
inline void VertexParameter::clear_dims() {
  dims_ = 0;
}
inline ::google::protobuf::int32 VertexParameter::dims() const {
  // @@protoc_insertion_point(field_get:intellgraph.VertexParameter.dims)
  return dims_;
}
inline void VertexParameter::set_dims(::google::protobuf::int32 value) {
  
  dims_ = value;
  // @@protoc_insertion_point(field_set:intellgraph.VertexParameter.dims)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace intellgraph

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_vertex_5fparameter_2eproto
